# Generated by Django 4.1 on 2022-09-29 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Exercise_name', models.CharField(max_length=50)),
                ('Exercise_type', models.CharField(max_length=40)),
                ('Exercise_difficulty', models.FloatField()),
            ],
        ),
    ]
